DotnetCore/PIAInterfaz/PIAInterfaz/Controllers/BolsaDeTrabajoController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PIAInterfaz.Data;
using PIAInterfaz.Models;
using PIAInterfaz.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PIAInterfaz.Controllers
{

 
    public class BolsaDeTrabajoController : Controller
    {
        private readonly UserManager<Usuario> userManager;
        private readonly MensajeRepository mensajeRepository;
        public BolsaDeTrabajoController(UserManager<Usuario> userManager, MensajeRepository mensajeRepository)
        {
            this.userManager = userManager;
            this.mensajeRepository = mensajeRepository;
        }
        public async Task<IActionResult> Index(bool showSuccessMessage = false)
        {

            var model = new ContactViewModel();
            if (User.Identity.IsAuthenticated)
            {
                var user = await userManager.GetUserAsync(User);
                model.Nombre = user.Nombres + " " + user.Apellidos;
                model.Email = user.Email;
            }
            ViewBag.ShowSuccessMessage = showSuccessMessage;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SendOpinion(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = await mensajeRepository.AddMessage(model);
                if (result != 0)
                {
               
                    return RedirectToAction(nameof(Index), new { showSuccessMessage = true });
                }
                return View("Error");
            }

            return View(model);
        }
    }
}

DotnetCore/PIAInterfaz/PIAInterfaz/Views/BolsaDeTrabajo/Index.cshtml
@model ContactViewModel
@{
    ViewData["Title"] = "Bolsa De Trabajo";
}

@section Styles {
    <link rel="stylesheet" href="~/css/jobstyles.css">
}

<main class="wrap">
    <div class="job-information">
        <h1>Bolsa de Trabajo</h1>
        <img src="img/jobPizza.jpg" alt="puestos de trabajo">
        <h2>Unete a nuestro equipo!</h2>
        <p>Estamos contratando:</p>
        <ul>
            <li>Gerentes</li>
            <li>Cajeros</li>
            <li>Cocineros</li>
            <li>Repartidores</li>
        </ul>
    </div>
    <form asp-controller="BolsaDeTrabajo" asp-action="SendOpinion">
        @if (ViewBag.ShowSuccessMessage)
        {
            <div class="success-message">Tu mensaje ha sido enviado correctamente.</div>
        }
        <h2>Contáctanos para mas información</h2>
        <label for="name">Nombre: </label>
        <input type="text" id="name" placeholder="Ingresa tu nombre:" asp-for="Nombre">
        <span class="validation-message" asp-validation-for="Nombre"></span>
        <label for="email">Correo Electrónico: </label>
        <input type="email" id="email" placeholder="Ingresa tu correo electrónico:" asp-for="Email">
        <span class="validation-message" asp-validation-for="Email"></span>
        <label for="rol">Selecciona un puesto</label>
        <select id="rol" asp-for="Asunto">
            <option value="Gerente">Gerente</option>
            <option value="Cajero">Cajero</option>
            <option value="Cocineros">Cocinero</option>
            <option value="Repartidor">Repartidor</option>
        </select>
        <span class="validation-message" asp-validation-for="Asunto"></span>
        <label for="message">Mensaje: </label>
        <textarea placeholder="Escribe aqui tu mensaje" id="message" asp-for="Mensaje"></textarea>
        <span class="validation-message" asp-validation-for="Mensaje"></span>
        <div asp-validation-summary="ModelOnly"></div>
        <button>Enviar</button>
    </form>
</main>