DotnetCore/PIAInterfaz/PIAInterfaz/Models/InicioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PIAInterfaz.Models
{
    public class InicioViewModel
    {
        public List<PizzaEspecialViewModel> PizzasEspeciales { get; set; }

        public List<ArticuloViewModel> MasVendidas { get; set; }

        public List<ArticuloViewModel> VuelveAOrdenar { get; set; }
    }
}

DotnetCore/PIAInterfaz/PIAInterfaz/Controllers/InicioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PIAInterfaz.Data;
using PIAInterfaz.Models;
using PIAInterfaz.Repository;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PIAInterfaz.Controllers
{
    public class InicioController : Controller
    {
        private readonly ILogger<InicioController> _logger;

        private readonly SignInManager<Usuario> signInManager;

        private readonly ArticuloRepository articuloRepository;

        public InicioController(ILogger<InicioController> logger, ArticuloRepository articuloRepository, SignInManager<Usuario> signInManager)
        {
            this.articuloRepository = articuloRepository;
            this.signInManager = signInManager;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            //TESTING SESSION
            HttpContext.Session.SetInt32("ClaveChida", 390);


            var pizzasEspeciales = await articuloRepository.getAllSpecialPizzas();
            var listOfPizzasEspeciales = pizzasEspeciales.GetRange(0, 4);

            var model = new InicioViewModel
            {
                PizzasEspeciales = listOfPizzasEspeciales
            };
            if (User.Identity.IsAuthenticated)
            {
                var listOfTopSellers = await articuloRepository.getTopSellers();
                model.MasVendidas = listOfTopSellers;

                var userLoggedInId = signInManager.UserManager.GetUserId(User);
                var listOfRecentArticles = await articuloRepository.getRecentArticlesByUser(userLoggedInId);

                model.VuelveAOrdenar = listOfRecentArticles;
            }




            return View(model);
        }

        [Route("/Inicio/Error/{code:int}")]
        public IActionResult Error(int code)
        {
            ViewBag.ErrorMessage = $"Ha ocurrido un error, codigo de error: {code}";
            ViewBag.CodeError = code;
            return View("Error");
        }
    }
}

DotnetCore/PIAInterfaz/PIAInterfaz/Controllers/MenuController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PIAInterfaz.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PIAInterfaz.Controllers
{
    public class MenuController : Controller
    {
        private readonly ArticuloRepository articuloRepository;
        private readonly IngredienteRepository ingredienteRepository;

        public MenuController(ArticuloRepository articuloRepository, IngredienteRepository ingredienteRepository)
        {
            this.articuloRepository = articuloRepository;
            this.ingredienteRepository = ingredienteRepository;
        }
        private bool ShowOnboarding(string name)
        {
            bool showOnboarding = true;
            if (HttpContext.Session.GetString(name) != null)
                showOnboarding = false;
            else
                HttpContext.Session.SetString(name, "Visited");
            return showOnboarding;
        }

        [Route("/Menu/PizzasBasicas")]
        public async Task<IActionResult> Index()
        {
            var pizzasBasicas = await articuloRepository.getAllBasicPizzas();
           
            ViewBag.ShowOnboarding = ShowOnboarding("Menu-PizzasBasicas");
            return View("BasicPizzas", pizzasBasicas);
        }
        [Route("/Menu/PizzasEspeciales")]
        public async Task<IActionResult> Specials()
        {
            var pizzasEspeciales = await articuloRepository.getAllSpecialPizzas();
            var ingredientes = await ingredienteRepository.getAllIngredients();
            ViewBag.IngredientsList = ingredientes;
            ViewBag.ShowOnboarding = ShowOnboarding("Menu-Specials");
            return View("SpecialPizzas", pizzasEspeciales);
        }

        [Route("/Menu/Espaguetis")]
        public async Task<IActionResult> Spaghettis()
        {
            var listOfSpaghettis = await articuloRepository.getAllSpaghettis();
          
            ViewBag.ShowOnboarding = ShowOnboarding("Menu-Spaghettis");

            return View(listOfSpaghettis);
        }

        [Route("/Menu/Complementos")]
        public async Task<IActionResult> Complements()
        {
            var listOfComplements = await articuloRepository.getAllComplements();

            ViewBag.ShowOnboarding = ShowOnboarding("Menu-Complements");
            return View(listOfComplements);
        }
        [Route("Menu/Bebidas")]
        public async Task<IActionResult> Drinks()
        {
            var listOfDrinks = await articuloRepository.getAllDrinks();

            ViewBag.ShowOnboarding = ShowOnboarding("Menu-Drinks");
            return View(listOfDrinks);
        }


    }
}

DotnetCore/PIAInterfaz/PIAInterfaz/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PIAInterfaz.Models;
using PIAInterfaz.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PIAInterfaz.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ArticuloRepository articuloRepository;
        private readonly IngredienteRepository ingredienteRepository;
        public ProductoController(ArticuloRepository articuloRepository, IngredienteRepository ingredienteRepository)
        {
            this.articuloRepository = articuloRepository;
            this.ingredienteRepository = ingredienteRepository;
        }

        private bool ShowOnboarding(string name)
        {
            bool showOnboarding = true;
            if (HttpContext.Session.GetString(name) != null)
                showOnboarding = false;
            else
                HttpContext.Session.SetString(name, "Visited");
            return showOnboarding;
        }

        [Route("/Producto/Especiales")]
        public async Task<IActionResult> Specials(int id = 0)
        {
            var pizzaEspecial = await articuloRepository.getSpecialPizza(id);

            var pizzasEspeciales = await articuloRepository.getAllSpecialPizzas();


            var elementoRepetido = pizzasEspeciales.SingleOrDefault(p => p.ID == id);
            pizzasEspeciales.Remove(elementoRepetido);

            var model = new SpecialPizzaProductViewModel()
            {
                Pizza = pizzaEspecial,
                ArticulosRelacionados = pizzasEspeciales
            };
            ViewBag.ShowOnboarding = ShowOnboarding("Product-Specials");
            return View("SpecialsProductPage", model);
        }

        [Route("/Producto/PizzaBasica")]
        public async Task<IActionResult> Basics(int id = 0)
        {
            var pizzaBasica = await articuloRepository.getPizzaBasica(id);
            var ingredientes = await ingredienteRepository.getAllIngredients();

            var articulosRelacionados = await articuloRepository.getAllBasicPizzas();

            var elementoRepetido = articulosRelacionados.SingleOrDefault(a => a.ID == id);
            articulosRelacionados.Remove(elementoRepetido);

            var model = new BasicPizzaProductViewModel()
            {
                PizzaInfo = pizzaBasica,
                Ingredientes = ingredientes,
                ArticulosRelacionados = articulosRelacionados
            };
            ViewBag.ShowOnboarding = ShowOnboarding("Product-Basics");
            return View("BasicsProductPage", model);
        }

        public async Task<IActionResult> Extras(int id = 0)
        {
            var product = await articuloRepository.getGenericArticleById(id);

            List<ArticuloViewModel> articulosRelacionados = null;
            switch (product.Tipo)
            {
                case TipoDeArticulo.BEBIDA:
                    articulosRelacionados = await articuloRepository.getAllDrinks();
                    break;
                case TipoDeArticulo.ESPAGUETI:
                    articulosRelacionados = await articuloRepository.getAllSpaghettis();
                    break;
                case TipoDeArticulo.COMPLEMENTO:
                    articulosRelacionados = await articuloRepository.getAllComplements();
                    break;
            }

            var articuloRepetido = articulosRelacionados.SingleOrDefault(a => a.ID == id);
            articulosRelacionados.Remove(articuloRepetido);
            var model = new ExtrasProductPageViewModel()
            {
                Articulo = product,
                ArticulosRelacionados = articulosRelacionados
            };
            ViewBag.ShowOnboarding = ShowOnboarding("Product-Extras");
            return View("ExtrasProductPage", model);
        }
        [Route("/Producto/Promocion")]
        public async Task<IActionResult> Offers(int id = 0)
        {
            var offer = await articuloRepository.getPizzaPromotionById(id);
            var ingredientes = await ingredienteRepository.getAllIngredients();
            var model = new PromotionProductPageModel()
            {
                Promotion = offer,
                Ingredientes = ingredientes
            };

            ViewBag.ShowOnboarding = ShowOnboarding("Product-Offers");
            return View("PromotionsProductPage", model);
        }


    }
}

DotnetCore/PIAInterfaz/PIAInterfaz/Views/Inicio/Index.cshtml
@model InicioViewModel
@{
    ViewData["Title"] = "Inicio";

    
}

@section Styles {
    @*<link rel="stylesheet" href="~/css/lightslider.css" />*@
}

<main class="@(!(User.Identity.IsAuthenticated) ? "main-page" : "")">
    <div class="slider">
        <div class="slides">
            <input type="radio" name="radio-btn" id="radio1" class="slide-radio">
            <input type="radio" name="radio-btn" id="radio2" class="slide-radio">
            <input type="radio" name="radio-btn" id="radio3" class="slide-radio">
            <input type="radio" name="radio-btn" id="radio4" class="slide-radio">
            <div class="slide first">
                <div class="slide-img" style="background-image: url('../img/pizzastock5.jpg');">
                    <div class="slide-content slide-content-right">
                        <h2>TRIO DE TRES</h2>
                        <p class="promotion-description">3 PIZZAS DE 3 INGREDIENTES A ESCOGER POR SOLO $299</p>
                        <div class="promotion-btns">
                            <a asp-controller="Producto" asp-action="Offers" asp-route-id="34" class="btn-red">Ordenar Ahora</a>
                        </div>
                    </div>
                </div>
                <!-- <img src="img/pizzastock3.jpg" alt=""> -->
            </div>
            <div class="slide">
                <div class="slide-img" style="background-image: url('../img/pizzastock7.jpg');">
                    <div class="slide-content">
                        <h2>DUO DE DOS</h2>
                        <p class="promotion-description">2 PIZZAS DE 2 INGREDIENTES A ESCOGER POR SOLO $199</p>
                        <div class="promotion-btns">
                            <a asp-controller="Producto" asp-action="Offers" asp-route-id="33">Ordenar Ahora</a>
                        </div>
                    </div>
                </div>
                <!-- <img src="img/pizzastock2.jpg" alt=""> -->
            </div>
            <div class="slide">
                <div class="slide-img" style="background-image: url('../img/pizzastock8.jpg');">
                    <div class="slide-content slide-content-right">
                        <h2>PIZZA RELLENA</h2>
                        <p class="promotion-description">PRUEBA NUESTRAS PIZZAS RELLENAS DESDE $149</p>
                        <div class="promotion-btns">
                            <a asp-controller="Producto" asp-action="Specials" asp-route-id="36" class="btn-red">Ordenar Ahora</a>
                        </div>
                    </div>
                </div>
                <!-- <img src="http://via.placeholder.com/1000x600" alt=""> -->
            </div>
            <div class="slide">
                <div class="slide-img" style="background-image: url('../img/pizzastock2.jpg');">
                    <div class="slide-content">
                        <h2>2 PIZZAS X $169</h2>
                        <p class="promotion-description">TODOS LOS DIAS</p>
                        <div class="promotion-btns">
                            <a asp-controller="Producto" asp-action="Offers" asp-route-id="35" class="btn-yellow">Ordenar Ahora</a>
                        </div>
                    </div>
                </div>
                <!-- <img src="http://via.placeholder.com/1000x600" alt=""> -->
            </div>
            <div class="navigation-manual">
                <label for="radio1" class="manual-btn manual-btn1"></label>
                <label for="radio2" class="manual-btn manual-btn2"></label>
                <label for="radio3" class="manual-btn manual-btn3"></label>
                <label for="radio4" class="manual-btn manual-btn4"></label>
            </div>
        </div>
    </div>
    <section class="recommended-section" >
        <div class="recommended wrap">
            <h2>PRUEBA NUESTRAS ESPECIALIDADES...</h2>
            <div class="products">
                @foreach (var pizza in Model.PizzasEspeciales)
                {
                    <div class="box">
                        <p class="product-title">@pizza.Nombre</p>
                        <img src="/Imagenes/GetImage?id=@pizza.ImagenID" alt="pizza" class="product-img">
                        <div class="details">
                            <p>@pizza.Descripcion</p>
                        </div>
                        <a asp-controller="Producto" asp-action="Specials" asp-route-id="@pizza.ID">Ordenar Ahora</a>
                    </div>
                }
            </div>
            <a asp-controller="Menu" asp-action="Specials">Ver Todas</a>
        </div>
    </section>
    @if (User.Identity.IsAuthenticated)
    {
        @if (Model.VuelveAOrdenar.Count != 0)
        {
            <section class="recommended-to-user">
                <div class="product-slider">
                    <h2>Vuelve a ordenar...</h2>
                    <ul class="autoWidth cs-hidden">
                        @foreach (var product in Model.VuelveAOrdenar)
                        {
                            <li class="item-a">
                                <div class="card-content">
                                    <img src="/Imagenes/GetImage?id=@product.ImagenID" alt="producto">
                                    <p class="card-title">@product.Nombre</p>
                                    <p class="card-description">@product.Descripcion</p>
                                    <span class="card-price">$@product.Precio</span>
                                    <a asp-controller="Producto" asp-action="@product.TipoAction" asp-route-id="@product.ID">Ordenar Ahora</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </section>
        }
        @if (Model.MasVendidas.Count != 0)
        {
            <section class="recommended-to-user recommended-black">
                <div class="product-slider">
                    <h2>LO MAS VENDIDO...</h2>
                    <ul class="autoWidth cs-hidden">
                        @foreach (var product in Model.MasVendidas)
                        {
                            <li class="item-a">
                                <div class="card-content">
                                    <img src="/Imagenes/GetImage?id=@product.ImagenID" alt="producto">
                                    <p class="card-title" title="@product.Nombre">@product.Nombre</p>
                                    <p class="card-description">@product.Descripcion</p>
                                    <span class="card-price">$@product.Precio</span>
                                    <a asp-controller="Producto" asp-action="@product.TipoAction" asp-route-id="@product.ID">Ordenar Ahora</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </section>
        }
}
  </main>


@section Scripts {

    <script>
        $('document').ready(function () {
            introJs(".slider").start();
            //$('.box').hover(function () {
            //    $(this).children('a,.details').show(300);
            //}, function () {
            //    $(this).children('a,.details').hide();
            //});
        });
        
    </script>

}